### ISSUE TITLE
Lambda keeping erroring out after successfully converting few instances

### ISSUE THREAD

**Issue by gamefundas** [AutoSpotting/AutoSpotting#351]
I am receiving the following error for all remaining instances after successful conversion of 12 of them.

> 2019/06/12 00:49:12 autoscaling.go:223: app-web-AppServerAG-xxxxxxxxxxxx skipping detaching on-demand due to failure to attach the new spot instance i-04d8d10exfgdf86b0

Its not clear what is causing the error besides the line above being printed repeatedly after it finds a spot instance to replace.

**Comment by gamefundas** [comment]
These are most likely because of service limits, Max no of Spot instance requests on the VPC. Found some errors in Cloud trails that pointed me to this. Will get rid of the limits and try again.

**Comment by gamefundas** [comment]
This is resolved but now I get the following error in some cases. Seems like #335 is the cause of this error as I noticed duplicates in my VPC as well

Error while switching normal instance to spot instance.
"Provided Load Balancers may not be valid. Please ensure they exist and try again."

**Comment by cristim** [comment]
That's a strange error, never saw it before.

Please provide the full logs for a run, with any critical data anonimized.

**Comment by gamefundas** [comment]
Many of them are failing to get rid of the old instances due to the load balancer error. Strangely AutoSpotting logs dont indicate any errors. The problem is that terminate instance fails behind the scenes with the load balancer error.

019/06/12 17:23:55 region.go:377: Stack: my-app
2019/06/12 17:23:56 region.go:385: Enabling group my-app-AppServerAG-LH6DXXXTGS4I for processing because its tags, the currently configured filtering mode (opt-in) and tag filters are aligned
2019/06/12 17:24:10 autoscaling.go:156: Adding instances to my-app-AppServerAG-LH6DXXXTGS4I
2019/06/12 17:24:10 autoscaling.go:96: Finding spot instances created for my-app-AppServerAG-LH6DXXXTGS4I
2019/06/12 17:24:10 autoscaling.go:468: my-app-AppServerAG-LH6DXXXTGS4I Counting already running on demand instances 
2019/06/12 17:24:10 autoscaling.go:484: my-app-AppServerAG-LH6DXXXTGS4I Found 1 on-demand instances running on a total of 1
2019/06/12 17:24:10 instance.go:628: Considering i-0470cXXX4dd8e1f93 for attaching to my-app-AppServerAG-LH6DXXXTGS4I
2019/06/12 17:24:10 autoscaling.go:147: us-east-1 Found spot instance: i-0470cXXX4dd8e1f93 Attaching it to my-app-AppServerAG-LH6DXXXTGS4I
2019/06/12 17:24:10 autoscaling.go:198: my-app-AppServerAG-LH6DXXXTGS4I Retrieving instance details for i-0470cXXX4dd8e1f93
2019/06/12 17:24:10 autoscaling.go:205: my-app-AppServerAG-LH6DXXXTGS4I i-0470cXXX4dd8e1f93 is in the availability zone us-east-1c looking for an on-demand instance there
2019/06/12 17:24:10 autoscaling.go:217: my-app-AppServerAG-LH6DXXXTGS4I found on-demand instance i-0a4XXXf8e77eb7e27 replacing with new spot instance i-0470cXXX4dd8e1f93
2019/06/12 17:24:11 autoscaling.go:439: us-east-1 my-app-AppServerAG-LH6DXXXTGS4I Terminating instance: i-0a4XXXf8e77eb7e27 

The only way I have been able to correct this is by manually deleting both (normal and spot) instances. Then have auto scaling kick in create the normal instance, then the lambda replacing it after 5-10 min. Not sure why it fails the first time when it tries to auto replace based on auto-spotting tags.

The load balancer error is visible only in the Cloudtrail logs (AttachInstance) request from AutoSpotting. Its seem to me that AutoSpotting is unable to disassociate the load balancer from  the previous instance cleanly and then attach to the new instance. May be AWS is preventing the action because the old instance is still associated with the ELB or some sequencing on the attachment needs a fix. Perhaps the old instance should be taken off the ELB as soon as the new spot instance gets created. The termination can happen in the grace period.

**Comment by cristim** [comment]
Thanks for the clarification.

AutoSpotting doesn't directly handle the load balancer membership, it's done under the hood when using the attach/detach/terminate API calls. And for those we have the right permissions.

I have no idea what would make this fail, except perhaps for API throttling or internal AWS issues. 
Can you still reproduce it with a new group?

Try to create an AWS support request about this if you have an enterprise support plan.

**Comment by gamefundas** [comment]
Makes sense. Will reproduce and then contact AWS support for an explanation on this.

**Comment by cristim** [comment]
Thanks, please keep me posted with the results.

**Comment by gamefundas** [comment]
I am unable to reproduce this now. Its possible someone tampered with the ELB's from the console that  drifted the instances in some way causing the problem. Will keep a watch on this if it happens again. For now lets close this issue.

**Comment by cristim** [comment]
Thanks!
